name: Dispatched ROCK build

on:
  repository_dispatch:
    types: [org-workflow-bot]

jobs:
  run_if_failure:
    if: ${{ !github.event.client_payload.passed }}
    runs-on: ubuntu-latest
    steps:
    - name: Debug print
      run: echo "${{ toJson(github.event.client_payload) }}"
    - name: Register the build back to the original repository's commit
      uses: SvanBoxel/organization-workflow@main
      with:
        id: ${{ github.event.client_payload.id }}
        callback_url: ${{ github.event.client_payload.callback_url }}
        sha: ${{ github.event.client_payload.sha }}
        run_id: ${{ github.run_id }}
        name: ${{ github.workflow }}
